Help : array of String = (
' Command parameters are separated by spaces and are separated from the command by a space. Use quotes (") to enclose parameters containing a space. For example:',
' add "This File.txt" ThatFile.txt',
' will add a file called ''This File.txt'' and another called ''ThatFile.txt'' to the image.',
'',
' Square brackets [] indicate optional parameters.',
' Ellipses ... indicate multiples of the same parameter.',
' Bar | indicate to use only one of the parameters.',
'',
' Valid wildcards are:',
' * : matches 0 or more characters',
' # : matches any character',
' | : when used before a search, it excludes these results from results already found',
'',
'access <file> [<attributes>]',
' Changes the file''s access rights, or attributes, to those given. Anything invalid is ignored. Filename can contain wildcards.',
'',
'add <file> [[<file>] ...]',
' Adds the files/directories listed in the local OS folder. Can contain wildcards.',
'',
'cat [<option>]',
' Displays a catalogue listing. If <option> is not given, then the current directory is shown. <option> can be one of the following:',
' all  : Displays a catalogue listing for the entire image.',
' dir  : Lists all the directories in the image.',
' root : Lists all the roots in the image.',
' os   : Displays a catalogue listing for the currently selected host directory.',
'',
'chdir [<dirname>]',
' Changes the host OS directory. If none specified then the current directory is shown.',
'',
'compact [<partition>]',
' Performs a compaction/defrag on the selected partition. If none specified, it acts on the current partition. Same as defrag.',
'',
'config [<setting> <option>]',
' Sets a configuration setting. Note that not all configuration settings are used by the console and could result in unpredictable behaviour.',
' <option> can be:',
' Boolean : True or False.',
' Integer : Decimal number, unless preceded by 0x, $ or & for Hex number.',
' String  : Anything.',
' Passing config with no parameters will list the valid options.',
'',
'create [<dirname>]',
' Creates a new directory. If no name given, ''NewDir'' is used instead.',
'',
'defrag [<partition>]',
' Performs a compaction/defrag on the selected partition. If none specified, it acts on the current partition. Same as compact.',
'',
'delete <file> [[<file>] ...]',
' Deletes the files/directories listed. Wildcards not allowed.',
'',
'dir <dirname>',
' Changes to directory <dirname>. Use ''^'' to specify the parent directory.',
'',
'dirtitle <title>',
' Changes the currect directory title.',
'',
'eject',
' Ejects the currently loaded image.',
'',
{$IFNDEF DIMCONSOLE}
'exit [togui]',
' With no parameter, quits console and application. Adding the togui parameter quits the console and opens the GUI application.',
{$ELSE}
'exit',
' Quits console and application.',
{$ENDIF}
'',
'exec <filename> <address>',
' Updates the execution address for <filename> to be <address>, which must be a valid hex number. Filename can contain wildcards.',
'',
'extract <file> [[<file>] ...]',
' Extracts all files/directories listed to the local OS folder. Filenames can contain wildcards.',
'',
'filetocsv <file> [[<file>] ...]',
' Outputs a CSV format of the specified files. Can contain wildcards.',
'',
'filetype <hex>|<name>',
' Translates the hex number to known ADFS filetype, or vice-versa.',
'',
'find <file> [[<file>] ...]',
' Finds the files/directories listed in the local OS folder. Can contain wildcards.',
'',
'fixdirs',
' Attempts to repair any broken ADFS directories.',
'',
'free',
' Displays the free space on the partition/side.',
'',
'from <file> add|find <file> [[<file>] ...]',
' Specifies an image file to use when adding or finding files, instead of the local OS folder. See add and find.',
'',
'insert <filename>',
' Inserts image specified by <filename>.',
'',
'interleave <option>',
' Changes the current interleave method and re-organises the data.',
' <option> can be 0, 1, 2, or 3 or auto, seq, int, or mux.',
' Only valid for Acorn ADFS L or FS.',
'',
'load <filename> <address>',
' Updates the load address for <filename> to be <address>, which must be a valid hex number. Filename can contain wildcards.',
'',
'list <filename>',
' Displays the file specified (BBC BASIC listing/text output/hex dump).',
'',
'ls',
' Display a catalogue of the current host OS directory. Same as cat os.',
'',
'new <format> [<option> [<option2>]]',
' Creates a new image:',
' <format> <option> <option2>  Result',
' DFS      S80                 Acorn DFS single sided 80 track',
' DFS      S40                 Acorn DFS single sided 40 track',
' DFS      D80                 Acorn DFS double sided 80 track',
' DFS      D40                 Acorn DFS double sided 40 track',
' WDFS     S80                 Watford DFS single sided 80 track',
' WDFS     S40                 Watford DFS single sided 40 track',
' WDFS     D80                 Watford DFS double sided 80 track',
' WDFS     D40                 Watford DFS double sided 40 track',
' ADFS     S                   Acorn ADFS S',
' ADFS     M                   Acorn ADFS M',
' ADFS     L                   Acorn ADFS L',
' ADFS     D                   Acorn ADFS D',
' ADFS     E                   Acorn ADFS E',
' ADFS     E+                  Acorn ADFS E+',
' ADFS     F                   Acorn ADFS F',
' ADFS     F+                  Acorn ADFS F+',
' ADFS     HDD                 Old map, Old directory 20MB',
' ADFS     HDD      OO<cap>[M] Old map, Old directory <cap> size',
' ADFS     HDD      ON<cap>[M] Old map, New directory <cap> size',
' ADFS     HDD      NN<cap>[M] New map, New directory <cap> size',
' ADFS     HDD      NB<cap>[M] New map, Big directory <cap> size',
' AFS      <level>  <cap>[M]   Acorn FS Level <level> of <cap> size',
' CFS                          Acorn Cassette Filing System',
' C1541                        Commodore 1541',
' C1571                        Commodore 1571',
' C1581                        Commodore 1581',
' AMIGA    DD                  Commodore Amiga DD',
' AMIGA    HD                  Commodore Amiga HD',
' AMIGA    HDD      <cap>[M]   Commodore Amiga hard drive of <cap> size',
' DOS+     640                 DOS+ 640K',
' DOS+     800                 DOS+ 800K',
' DOS      360                 DOS 360K',
' DOS      720                 DOS 720K',
' DOS      1440                DOS 1.44MB',
' DOS      2880                DOS 2.88MB',
' DOS      HDD      <cap>[M]   DOS hard drive of <cap> size',
' <cap> is specified in KB, or MB if M is included.',
'',
'opt <option> [<side>]',
' Sets the boot option for the current side, or <side> if specified.',
' <option> can be 0, 1, 2, or 3, or can be none, load, run, or exec.',
'',
'rename <oldfilename> <newfilename>',
' Renames <oldfilename> to <newfilename>.',
'',
'report',
' Displays the image report.',
'',
'runscript <filename>',
' Runs a script. Cannot be used if one is already running.',
'',
'save [<filename>] [<compressed>]',
' Saves the current inserted image to the host OS.',
' If a UEF is required to be compressed, pass ''TRUE'' as the second parameter.',
'',
'savecsv [<filename>]',
' Outputs the contents of the currently loaded image in CSV format.',
'',
'search <file> [[<file>] ...]',
' Finds all files/directories listed. Filenames can contain wildcards. See from command to find files/directories on images which are not inserted.',
'',
'status',
' Displays the current configuration settings.',
'',
'stamp <file>',
' Timestamps the specified file with the current time and date.',
'',
'title <title> [<side>]',
' Sets the disc title for the current side, or <side> if specified.',
'',
'type <file> <filetype>',
' Updates the filetype for <filename> to be <filetype>, which must be a valid hex number. Filename can contain wildcards.');
