DOSFileTypes: array[1..23] of String = (
'sysWindows System',
'cmdWindows Command',
'datData',
'exeExecutable',
'comDOS Command',
'batBatch',
'hlpWindows Help',
'appFoxPro Generated Application',
'rscResource',
'fmtFoxPro Format',
'infSetup Information',
'patPattern',
'accGEM Accessory',
'icnWindows Icon',
'fntWindows Font',
'docWord Document',
'gemGEM Metafile',
'imgGEM Image',
'txtText',
'$$$Temporary',
'iniWindows Initialisation',
'binBinary',
'cfgConfiguration');